application: my-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: core.wsgi.application
  login: admin
  secure: optional

- url: /static/
  static_dir: frontend/build/
  secure: optional

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: optional

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: core.wsgi.application
  secure: optional
  login: admin

- url: /.*
  script: core.wsgi.application
  secure: optional

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - (.*)\.pyc
    - node_modules
    - static/dev
    - static/src
